### ISSUE TITLE
Meta-upstream

### ISSUE THREAD

**Issue by monochromem1nd** [PrismLauncher/meta-upstream#1]
Is there any way to use great meta of this repository?) is there an api for this upstream?

**Comment by TayouVR** [comment]
you can reach the generated data through https://meta.prismlauncher.org/v1/
If you are planning to use it for your own launcher though, it would probably be a good idea to deploy a version to your own website. (e.g. meta.aurora-launcher.ru)

**Comment by monochromem1nd** [comment]
Hmm, interesting option, thx!
